### ISSUE TITLE
Unable to Mount Directories Properly

### ISSUE THREAD

**Issue by AhmadAmmar** [EL-BID/Building-Detection#1]
**My commands:**

`export IDB_DATA_DIR="/media/splash/00F2D259F2D25310/Data/idb-data-bundle-2-19"`
`sudo scripts/console`
`${IDB_DATA_DIR} -> /opt/data`
`idb -> /opt/src/idb`
`rastervision run local -e idb.experiment`

**Error:**

`Ensuring input files exist    [####################################]  100%
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/src/rastervision/__main__.py", line 17, in <module>
    rv.main()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/src/rastervision/cli/main.py", line 159, in run
    dry_run=dry_run)
  File "/opt/src/rastervision/runner/experiment_runner.py", line 153, in run
    unique_commands, rerun_commands, skip_file_check=skip_file_check)
  File "/opt/src/rastervision/runner/command_dag.py", line 61, in __init__
    '\t{}\n'.format(',\b\t'.join(missing_files)))
rastervision.core.config.ConfigError: Files do not exist and are not supplied by commands:
	/opt/data/input/paramaribo/imagery/PARAMARIMBO_2015_ORTO_1_1.tif,       /opt/data/input/georgetown/aois/2.geojson,      /opt/data/input/paramaribo/aois/paramaribo-aoi1_8_0.geojson, /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C4R3.tif, /opt/data/input/belice/imagery/new_belice.tif,       /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C1R2.tif, /opt/data/input/georgetown/aois/5.geojson,   /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C2R1.tif, /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C4R2.tif,      /opt/data/input/paramaribo/aois/paramaribo-aoi1_7_0.geojson,    /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C2R3.tif,      /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C4R1.tif, /opt/data/input/belice/aois/3.geojson,       /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C3R1.tif, /opt/data/input/paramaribo/aois/paramaribo-aoi1_4_0.geojson, /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C1R3.tif, /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C3R2.tif,      /opt/data/input/belice/aois/2.geojson,  /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C1R1.tif,      /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C2R2.tif, /opt/data/input/georgetown/imagery/Guyana_2017-2018-50cm_BGRN_C3R3.tif,      /opt/data/input/georgetown/aois/1.geojson,      /opt/data/input/belice/aois/1.geojson
`

Can you please guide me where am I doing it wrong?

Commands and error screenshot:

![Screenshot from 2019-06-07 11-47-32](https://user-images.githubusercontent.com/9590856/59086077-10788680-891a-11e9-84d3-169d5f053142.png)

My data directory structure:

![Screenshot from 2019-06-07 11-49-49](https://user-images.githubusercontent.com/9590856/59086196-6d743c80-891a-11e9-9b66-0e566caf1d63.png)

**Comment by lewfish** [comment]
Could you manually check inside the container to see if the files are there? ie. run

```ls /opt/data/input/paramaribo/imagery/PARAMARIMBO_2015_ORTO_1_1.tif```

If not is anything in `/opt/data`?

Also, 
```
${IDB_DATA_DIR} -> /opt/data
idb -> /opt/src/idb
```
copied from the README aren't commands, they're just to illustrate what is mounted to what.

**Comment by pierreki** [comment]
for windows how would the commands be, I've been trying for days
